baseURL = "https://www.example.com"
disqusShortname = ""
languageCode = "en-us"
languageName = "En"
paginate = "5"
theme = "persian"
title = "Persian"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "categories/nature/"
name = "Category"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "privacy-policy"
name = "Privacy Policy"
weight = 5
[outputs]
home = ["HTML", "RSS", "json"]
[params]
author = "Jane Doe"
contact_form_action = "#"
copyright = ""
description = "This is meta description"
logo = "https://www.google.com/url?sa=i&url=https%3A%2F%2Fbrandedx.com.au%2F&psig=AOvVaw2fu5cHnrXQkDa6CC2MKsFV&ust=1602343938679000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCODo9bzqp-wCFQAAAAAdAAAAABAD"
search = true
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-facebook"
link = "#"
title = "facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
title = "twitter"
[[params.social]]
icon = "ti-instagram"
link = "#"
title = "instagram"
[[params.social]]
icon = "ti-github"
link = "#"
title = "github"
[[params.social]]
icon = "ti-linkedin"
link = "#"
title = "linkedin"
